### ISSUE TITLE
FR : Please implement a feature that provides panels created by makePanel().

### ISSUE THREAD

**Issue by pllap** [Thunder-cut-2020/WhiteBoard-Client#18]
**Is your feature request related to a problem? Please describe.**
The image that is sent from the server has to be displayed in the participant panel, and there is no way to access to the panel.
I need a method that provides panel of each participant.

**Describe the solution you'd like**
The number of panels is managed by ID now, so I think you can save them to a List.
And then you can implement a method that provides List itself, or a member(panel) of a List.

**Describe alternatives you've considered**
I think there are other ways to manage panels, for example, to create a class that has ID and JPanel, for convenience.

**Additional context**
For now, I think, Variable ID in the class ParticipantsPanel is ambiguous.
I understand that it just indicates how many panels we have, and nothing anymore.
If you make List of panels, purpose of this variable could be obvious.

**Comment by Kasania** [comment]
This was added on #22
