### ISSUE TITLE
BUG : Undo feature is not working when use undo feature 10 times

### ISSUE THREAD

**Issue by susemeeee** [Thunder-cut-2020/WhiteBoard-Client#25]
**Describe the bug**
Undo feature is not working when use undo feature 10 times

**To Reproduce**
1. Draw 10 lines
2. Undo 10 times
3. Draw 1 line
4. Undo 1 time
5. See error

**Expected behavior**
The "undo" feature operates normally.

**Additional context**
You can fix with workdatalist array

**Comment by Kasania** [comment]
Fixed on #24.
