### ISSUE TITLE
BUG : Default encoding of each users are different

### ISSUE THREAD

**Issue by pllap** [Thunder-cut-2020/WhiteBoard-Client#40]
**Describe the bug**
The project's default encoding is not specified. Because of this, some users run programs as UTF-8 and some as MS949. Thus you will see garbled characters when chatting. 

**To Reproduce**
1. Type chat message.
2. Send the message by pressing the Enter button.
3. Chat message is shown garbled.

**Expected behavior**
The message you sent is shown to the chat screen intactly.

**Comment by sjy5386** [comment]
Do **not** use _MS949_.
Use _UTF-8_ only.

**Comment by Kasania** [comment]
> Do **not** use _MS949_.
> Use _UTF-8_ only.

I agree.
